### ISSUE TITLE
Expose a property notifying if field has been validated

### ISSUE THREAD

**Issue by janpieterz** [formstate/formstate#12]
I want to keep my fields 'default' gray until they have been acted upon (data entered), then go either into error mode (red) or valid mode(green).
I currently do this using the 'hack' `(this.props.value as any).lastValidationRequest > 0`.
I'd like to make this a first class concept. The validators for, for example, a required value, rightfully only kick in **after** adding 1 character and removing, the library should expose this concept of having validated or being in an unknown/unvalidated state.

I propose on the FieldState class:
``` ts
@computed public get hasBeenValidated() : boolean {
    return this.lastValidationRequest > 0;
}
```

Let me know if you'd like this, happy to make a pull request! If there's a more supported way per-field to allow this to happen I'd be happy to use that of course :)

**Comment by basarat** [comment]
> I propose on the FieldState class:

slightly dangerous cause `reinitValue` : https://github.com/formstate/formstate/blob/58f78bae160878ddee80ed21a7fcddefd4109d5e/src/core/fieldState.ts#L79 should probably reset the `hasBeenValidated` as well, but using `lastValidationRequest` for this wouldn't work. 

We can add an explicit `this.hasBeenValidated:boolean` that we track in `onChange` `reinitValue` and `validate`. Happy to take a PR :rose:

**Comment by janpieterz** [comment]
Fixed.
I don't suppose I could tempt you to release a new version with only this change? 😄 
Cheers for accepting the merge btw!

**Comment by basarat** [comment]
> Cheers for accepting the merge btw!

Thanks for using :rose: :heart: `0.17.0`
