### ISSUE TITLE
Allow hook for change to error state

### ISSUE THREAD

**Issue by janpieterz** [formstate/formstate#14]
I've got this form where two elements depend on each other. There is a 'site' selector, and depending on what comes out of that selector the Date(s) selector blanks out certain dates that are invalid for that site.

I'm trying to get this hooked up using the hooks of the field, but don't get very far. The below .gif shows. 
The `onUpdate` triggers way too often for me to be usable (it would involve requests to the API). 

The validation debounce is also perfect for this (someone clicking quickly through this should not trigger the requests), but the `on$ChangeAfterValidation` apparently does not trigger after invalidating.

I got three ideas:

- Add parameter to on$ChangeAfterValidation indicating status (hasError: boolean). The name seems to allow both error and non error states (AfterValidation doesn't indicate success/failure). This would be the most true to the meaning + allow better sustainability with upgrades (see next option).
- Trigger on$ChangeAfterValidation on failures too. This would probably be the easiest, but people depending on the library might be surprised if they already attach to this hook and it triggers more, potentially breaking a lot of integrations.
- Separate on$ChangeAfterError. This speaks for itself. Could also be added while also doing one of above, with another added hook on$ChangeAfterValid

Let me know your thoughts, would be happy to implement

**Comment by basarat** [comment]
> The below .gif shows.

gif missing 😢 :rose:

**Comment by janpieterz** [comment]
My bad, see here, when removing JP01 from the selected sites. :

![formstate validation hooks](https://cloud.githubusercontent.com/assets/383634/23101265/ba900bae-f68f-11e6-984f-09cb1a80ddcb.gif)

**Comment by basarat** [comment]
you can just `onUpdate(utils.debounce(()=>{doXHR()},1000))`

**Comment by janpieterz** [comment]
Yeah I got something like that now. Was just wondering if we should make it more of a first class concept

**Comment by basarat** [comment]
I'm just scared of the order of callbacks. `$`,`value`,`error` are the three key things we track but its difficult for me to know exactly which order to calls these and under what conditions. Closing for now :rose:
