### ISSUE TITLE
Allow debounce timeout default to be set to a different value

### ISSUE THREAD

**Issue by janpieterz** [formstate/formstate#15]
Similar to for example mobx's `useStrict(true)`, I'd love to be able to set the debounce timeout as a default to a different value than the current 200.

For most of my fields a different value (25) works smoother, except in certain cases where there are API calls etc and the debounce is beneficial when higher. 

Adding this to each `FieldState` feels like a bit of unnecessary boilerplate.

Setting it globally would of course mean introducing some kind of global `formstate` singleton, which though offering this as an option might be inadvisable.

As an other option, it could possibly be added to the `FormState` constructor which would subsequently set it on each child `FieldState` except if different than the default. Still a bit of boilerplate but possible a better option given that no global state is created for this. 

For big forms (I got one with a shocking 29 fields) this would greatly reduce the boilerplate.

**Comment by basarat** [comment]
> Adding this to each FieldState feels like a bit of unnecessary boilerplate.

You can customise `FieldState` as much as you want with your own `FieldState`: :rose:

```ts
export class MyFieldState<TValue> extends FieldState<TValue> {
}
```

**Comment by janpieterz** [comment]
That was easy enough ;)
