### ISSUE TITLE
Regarding error messages

### ISSUE THREAD

**Issue by spion** [formstate/formstate#2]
I was thinking, it might be nice if the error messages themselves are left out of the design. Instead, every validator would have a name, and the view could handle doing the error message display, e.g.

```jsx
fieldState.errors('errorName') ? <p> error message here</p> : null
```

This would make it easier to add dynamic content (like help etc) to errors, as well as to do localisation / translation.

The validator becomes a boolean function f(x) -> true if valid, false if not

**Comment by basarat** [comment]
First off, highly appreciate your review  ❤️  x 💯  

> The validator becomes a boolean function f(x) -> true if valid, false if not

But you would need to store the error message somewhere. Moving them out of the `validator` forces you to maintain it elsewhere only to reconcile it later. 

> This would make it easier to add dynamic content (like help etc) to errors

You can create validation creation functions quite easily. e.g. 

```ts
const minVal = (minVal) => (val) => val < minVal && `The value must be greater than ${minVal};

// Usage 
validators: [minVal(100)]
```

You can follow a similar pattern to have validators that customize their error messages.  Also for localization we have done : 

```ts
const myValidator = (val) => someCondition && localize('myValidatorError');
```

Where `localize` is a `key => localized-string` function. 

Hope this helps :rose: :heart:

**Comment by basarat** [comment]
> errors('errorName')

also don't want strings. and validators are stored in an array in order to be applied deterministially sequentially so can't be named aka `validators:{name:validator}`, we could `[{name,validator}]` but again ... losely typed strings ... can be made typesafe by putting it behind a function ... but haven't been convinced of a use case that can't be easily handled

**Comment by spion** [comment]
Agreed with not wanting strings. Would be nicer if the validations are a proper record, something like

```tsx
validate<TField, V>(validations:{[Key in keyof V]:(f:TField) => boolean ):{[Key in keyof V]:boolean}
```

But regarding the error message, it would be stored in the view:

```tsx
{fieldState.errors.errorName ? <p>Message for the error goes here. Its also easy to add a <Link>link to the documentation</Link></p>: null}
```

How to show the error is a view concern. It may involve elements such as links, interactive help and so on. As such I don't really see it belonging within the validation logic. 

Additionally, there is just too much that isn't very clear for the end user if the validator includes the message. Lets say its a minimum value validator. What sort of value is it? "The value must be greater than ${minVal}" is very unspecific. Is it a price bid? Then we probably want to tell the user something like, "The minimum bid is set at $1". Is it age? In that case we want "Sorry, you must be 13 or older to use this website". But do we want to write a separate minimum value validator for every separate minimum value message? Not really... So to me it seems like it would be nicer if the message can be separated from the validation.

**Comment by basarat** [comment]
> t may involve elements such as links, interactive help and so on. 

Adding a link is indeed something very view specific. You could let the validator return `'errorh34r7'` and then in the ui `field.error == 'errorh34r7' ? yourUI : field.error`. 

> The value must be greater than ${minVal}" is very unspecific.

Its very business specific. If you want it to say `"The minimum bid is set at $1"` I would rather have it just in the validator `(val)=> val<1 && "Minimum bid is $1"` and then test this function *without* have to spin up the whole UI.

**Comment by basarat** [comment]
> "The minimum bid is set at $1". Is it age? In that case we want "Sorry, you must be 13 or older to use this website"

Function that handles both of these

```ts
const minVal = (minVal, message) => (val) => val < minVal && message;

// usage 
minVal (1,"The minimum bid is set at $1");
minVal (13,"Sorry, you must be 13 or older to use this website");
```
And its completely UI framework independent :heart:
