### ISSUE TITLE
Non async validate

### ISSUE THREAD

**Issue by tomitrescak** [formstate/formstate#21]
Hi, you specify that return type of `validate` is `Promise<{ hasError: true } | { hasError: false, value: TValue }>`. This looks like it is possible to do sync validation. Yet, I cannot make it work as I always have to call it with `await`.

I could really use sync version as it's much easier to test as well. Am I missing something? Thanks!

**Comment by tomitrescak** [comment]
Nevermind ... it's not possible.

**Comment by tomitrescak** [comment]
Actually, would it be possible to add synchronous validations? This async calls are adding quite big overhead on testing. To be honest I do not even know how to approach it, since async validations are performed normally inside the components' functions. 

To test, I'd have to extract all methods to it's own view model and separate unit tests into two, unit tests of view model and unit tests for component calling the view model. While this may be the best possible way, it also adds quite a lot of complexity.

**Comment by basarat** [comment]
> unit tests of view model and unit tests for component calling the view model. While this may be the best possible way, it also adds quite a lot of complexity.

I simply test the validators on their own. e.g. 

```ts
// appValidators.ts
const required = (val) => !val && 'required';

// Test 
describe( '', () => {
  it('', () => {
   assert.equal(required(''), 'required'); 
   // so on
  }); 
}) 
```

I trust formstate to use the validators reliably as formstate has its own tests.

Also `async` tests aren't hard with e.g. mocha and `async/await` : https://github.com/formstate/formstate/blob/fc9b6e56d497323808706284fd4cb86635b5eba1/src/tests/formState/validation.ts#L29-L41 

```ts
  it("should validate a nested FieldState and fail if invalid", async () => {
    const name = new FieldState('').validators(
        (val) => !val && 'value required'
    );
    const form = new FormState({
      name,
    });
    const res = await form.validate();
    assert.equal(res.hasError, true);
    assert.equal(form.hasError, true);
    assert.equal(form.error, 'value required');
    assert.equal(form.$.name.error, 'value required');
  });
```

So if you want sync validators for testing alone, async/await solves that so don't need it. Hope that helps :rose:
