### ISSUE TITLE
Way to get plain values of FormState?

### ISSUE THREAD

**Issue by Strate** [formstate/formstate#25]
Seems that there is no method such as `getValues()` to just get plain values of the form, without need to do something like that:

```
const form = new FormState({
  a: new FieldState(""),
  b: new FieldState("")
})

function doSumbit() {
  const submitValue = form.getValue() // not possible, should do this:
  const submitValue = {
    a: form.$.a.$,
    b: form.$.b.$,
  }
}
```

This could become too deep with nested forms :)

P.S. Thank you for library!

**Comment by basarat** [comment]
> This could become too deep with nested forms :)

Indeed. But its the cost of TypeSafety. There are ways to model it with TypeScript 2.0 mapped types and I did experiment with that but the magic would break in subtle ways (TypeScript would infer one thing but the runtime would be another) so for now you have to do it manually :rose:
