### ISSUE TITLE
Can't spread FieldState to react component, because `onChange` is not own property

### ISSUE THREAD

**Issue by Strate** [formstate/formstate#26]
```ts
const field = new FieldState()

<component {...field />
```

Component do not receive `onChange` prop, because it is not "own" property. I can suggest you to make it own, or to instroduce special method to allow spread to component.

**Comment by basarat** [comment]
> Component do not receive onChange prop

Component should receive `field`. It should use `props.field.value` and `props.field.onChange`. Hope that helps :rose:  

Covered in demo of how to create a Field components : https://formstate.github.io/demos/ :heart:

**Comment by Strate** [comment]
@basarat of course, component should use `value` and `onChange`. But please note, that I mentioned "spread" properties.
Assume you have properties:
```ts
const props = {
  value: void 0,
  onChange: function() {}
}
```
passing them via spread operator:
```
<component {...props} />
```
is the same as:
```
<component value={props.value} onChange={props.onChange} />
```
but this is not works with `FieldState`, because `onChange` is *not own property*, it is *inherited* property, and spread operator works only with own properties. This could be easily solved in the library.

**Comment by basarat** [comment]
> This could be easily solved in the library

I am not sure I understand. Can you provide an example of why current code will not work and would need changing : https://github.com/formstate/formstate/blob/f100d1e8d0227a89c6bbfa6942b649ae07f0a3bb/src/core/fieldState.ts#L91 Thanks :rose:

**Comment by basarat** [comment]
Been open for a while, closing till an example is presented :rose:
