### ISSUE TITLE
FormState with ObservableArrays

### ISSUE THREAD

**Issue by piotrwitek** [formstate/formstate#29]
Hi,
I have formState which is an observable array of collection of input field states, and I have a problem with typing the Array as Observable Array.

Here is an example:

```ts
type Fields =
  FormState<{
    conditionFieldState: FieldState<string | undefined>,
  }>;

const formState = new FormState<Fields[]>([]);

formState.$.replace(
  formState.$.filter((item, itemIndex) => itemIndex !== index),
); // Error: Property 'replace' does not exist on type 'FormState<{ conditionFieldState: FieldState<string | undefined>; }>[]'
```

I would like to find an elegant way to have my Array to be an ObservableArray type from mobx (thus fixing compiler error for missing replace property)

@basarat could you please help and show me some example how you would do it?

**Comment by basarat** [comment]
> I would like to find an elegant way to have my Array to be an ObservableArray type from mobx (thus fixing compiler error for missing replace property)

Annotate it as an observable :rose: 

```ts
import { FormState, FieldState } from 'formstate';
import { IObservableArray, observable } from 'mobx';
type Fields =
  FormState<{
    conditionFieldState: FieldState<string | undefined>,
  }>;

const formState = new FormState<IObservableArray<Fields>>(observable([]));
const index = 0;
formState.$.replace(
  formState.$.filter((item, itemIndex) => itemIndex !== index),
);
```

**Comment by piotrwitek** [comment]
@basarat thanks a lot, works like a charm, I need to dig more into mobx, seems really nice :)
