### ISSUE TITLE
How to get a object with values only?

### ISSUE THREAD

**Issue by thupi** [formstate/formstate#30]
Hey, first of all this is amazing package comprared to many other over complicated implementations :-) 

I would like to have a method which would deliver a object with values only.

That would mean that i shouldn't have to destructure the fields everytime i have to post it to a server :-)

I think this would be a great improvement :-)

**Comment by basarat** [comment]
Thanks :rose:

> I would like to have a method which would deliver a object with values only. That would mean that i shouldn't have to destructure the fields everytime i have to post it to a server :-)

Any declarative manner for this results is equal (and less safe) code than just doing it. If you find yourself doing it more than once for the same set of fields consider making a utility function :rose:

**Comment by basarat** [comment]
> Any declarative manner for this results is equal (and less safe) code than just doing it.

Not an absolute fact. Just an observation of a number of solutions already out there :rose:
