### ISSUE TITLE
Support to get list errors instead of one error for form.error

### ISSUE THREAD

**Issue by hoangta79** [formstate/formstate#31]
Currently, library only support to get first error in form. Can we make it to support get list errors in validated form? Thanks.

**Comment by basarat** [comment]
> Can we make it to support get list errors in validated form?

You can inherit to add any such additional functionality. You will get access to `getValues` which you can simply map over to get `errors` for all values. 

Similar to what `error` does : https://github.com/formstate/formstate/blob/f100d1e8d0227a89c6bbfa6942b649ae07f0a3bb/src/core/formState.ts#L114-L117 :rose:
