### ISSUE TITLE
Question:  API for setting form state

### ISSUE THREAD

**Issue by rhythnic** [formstate/formstate#33]
I'm excited to try formstate.  I like the API.  I apologize if this is in the docs and I've missed it, but is there a way to set form state via an object?  For editing as opposed to creating an entity, can you pass in the object that has the entity's current values?

**Comment by basarat** [comment]
> For editing as opposed to creating an entity, can you pass in the object that has the entity's current values?

I haven't see a typesafe implementation of Object -> Object<T> -> Object that doesn't cause more confusion yet (sadly). So no. The object is to provide great safety and you can normally write code without me coming up with a declaration API https://github.com/formstate/formstate/issues/30#issuecomment-307552522 :rose:
