### ISSUE TITLE
Infinite loop while validating

### ISSUE THREAD

**Issue by oyvindberg** [formstate/formstate#37]
I managed to narrow it down somewhat: A nested form with compose() on the outer (with validators or not) with at least two `onChange` will trigger an infinite loop.

**Comment by oyvindberg** [comment]
@basarat do you have time to take a look?

**Comment by oyvindberg** [comment]
Ok, it was quicker to just fix it myself. WDYT about the change?

**Comment by basarat** [comment]
Released with `0.24.0` :rose: 

I only have `Form{Field,Field}.compose`. `Form {Form{Field,Field}}.compose` may or may not work. Currently it was infinite looping (as you identified) but don't have a concrete use case for such composition personally so YMMV 👍  

Thanks for the PR :heart:
