### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by tomitrescak** [formstate/formstate#4]
Hi, Basarat, great work as usual ;) Already using it in my project. I have one question though about array. How do you specify a field that contains an array of complex objects. In your docs you have two form states, is that necessary?

TL;DR;

So, can a `FieldState` contain an array of `FormStates` as its value?

Example:

```js
class A {
  a: number;
  b: string;
}

class B = {
  arr: A[]
}
```

can I model it like this?

```js
// i like to have all types globally available in order to reduce imports, don't judge ;)
declare global {
  namespace App.Models {
    type AStateFields = {
      a: FieldState<number>;
      b:  FieldState<string>;
    }

    type BStateFields = {
      arr: FieldState<AStateModel[]>;
    }

    type AState = AStateModel;
    type BState = BStateModel;
  }
}

class AStateModel extends FormState<App.Models.AStateFields> {
  constructor(a: A) {
    super({
      a: new FieldState(a.a),
      b: new FieldState(a.b),
    })
  }
}

class BStateModel extends FormState<App.Models.BStateFields> {
  constructor(b: B) {
    super({
      arr: new FieldState(b.map(item => new AStateModel(item)))
    })
  }
}
```

**Comment by tomitrescak** [comment]
And one more question, how do I make FromState react on changes in my arrays? Initialising it as before, no changes are being reated upon when I add or remove object from array..

[EDIT 1]

When I initialise my array as `new FieldState({value: my_array_of_field_states})` Then the observable array is created, but I'm pretty sure it will not validate every element of the field set array.

[EDIT 2]

Would this be the answer?

`new FormState({value: observable(my_array_of_field_states)})`

**Comment by basarat** [comment]
Sorry for the delay in replying but the question confused me for a while + holidays didn't help :) :rose: 

> How do you specify a field that contains an array of complex objects.

I think this is the core of your question. As an example we have drop downs (html `select`) that need to be bound to `{display:string, value: string}`. We have it simply as :


```tsx
const arr = new FieldState<DisplayValue>({
   value: {display:'none', value: ''},
   validators: [(val)=>!val.value && 'Value required']
});
```

Expand that to an array just a easily: 

```tsx
const arr = new FieldState<DisplayValue[]>({
   value: [{display:'none', value: ''}],
   validators: [(val)=> (!val.length || !val[0].value) && 'Value required']
});
```

> how do I make FromState react on changes in my arrays

You don't. Just use a fieldState as mentioned. Basically you make sure you call `onChange`. That in turn ensures that the validators get called. You are free to reuse the array `currentArray.push(newValue); onChange(currentArray)` if you want or use `onChange(currentArray.concat([newValue]))`.  The only reason *anything* here is observable is to allow you to easily bind to the UI. We don't actually use / or recommend using, the power of mobx for anything else. At least a use case hasn't come up yet :rose:

**Comment by tomitrescak** [comment]
@basarat, thanks for the answer, makes sense. but what if that array contains objects that contain arrays of objects .... I'm aiming at complex forms with multi level display. I need everything to validate and react to changes accordingly.

**Comment by basarat** [comment]
> but what if that array contains objects that contain arrays of objects .... I'm aiming at complex forms with multi level display

Tips: 
* Use `FieldState` whenever you can as `onChange` does validation automatically for you. 
* Use `FormState` to collect all the fields for a final call to `validate` before sending data to the server. 

FormState is not automatic in any sense e.g. 

```ts
const field1 = new FieldState({value:'', validators:[(val)=>!val && 'Value required']});
const field2 = new FieldState({value:'', validators:[(val)=>!val && 'Value required']});
const form = new FormState({field1,field2});

// Note : No validation has run upto this point. So: 
console.log(form.hasError); // false

await field1.validate(); 

// Field 1 has error right now. 
console.log(form.hasError); // true

// Fix error in field 1
field1.onChange('something');
await field1.validate(); 

// Field 2 still has error but hasn't been validated yet so: 
console.log(form.hasError); // false

// The only guarantee that the form is validated:
await form.validate();
console.log(form.hasError); // true!
```

So really you should *always* call `form.validate` *right before* sending the data to the server and then all the `$` values are a snapshot of validated values :rose:

**Comment by tomitrescak** [comment]
I am still struggling. I guess the best is the example and please tell me if I think is ok. I'll keep it as simple as I can.

Data Structure

```js
class Car 
  name: string // required 
  features : string[] // at least one
  accessories: Accessory[] 

class Accessory {
  name: string // required
  price: number // positive int
  ...
}
```

The goal is to show and validate ALL data.
* Name of the car is shown in input
* All features are shown in list of inputs with ability to delete any feature or add new one with the click of the button, each feature cannot be empty
* All accessories are shown as tabs, with each tab holding details of each accessory. We can add  or remove accessories.

Now, this is how I design my formstate, which according to your instructions is not correct as I use observable arrays. Also I'm not sure if that form state for accessories is necessary. You mention to use onchange... but where? When I click on the button, where do I trigger it?

```js
var state = new FormState({
  name: new FieldState({value: name, validator: ... required})
  features:  new FieldState({value: observable(features), validator: ... at least one}) // how do I validate individual elements? Is observable ok here?
  accessories = new FormState(observable(accessories.map(a => { // is formstate a correct use for this? What bout that observable?
    name: new FieldState({value: a.name, validator: ... required}),
    price: new FieldState({value: name, validator: ... positive int})
  })))
})
```

**Comment by basarat** [comment]
I'll create an example once I'm done with my next thing  .... an example creating library : https://github.com/basarat/eze / http://basarat.com/eze/ :D :rose:

**Comment by tomitrescak** [comment]
Yea, I already was spying on EZE it yesterday night ;) Looks good so far! couple remarks of what I do not like and what I like with storybook

Positive

+ integration with JEST snapshots (biggest selling point for me)
+ possibility to run other tests (mocha, jest ... via plugin)
+ view all stories
+ plugin system

Negative

- no hierarchical views of stories
- forces own architecture (webpack + babel ...)
- no typescript integration
- dodgy documentation possibilities (looks nice but has bugs)
- runs in separate process (I would love to have this as part of my app under specific URL, with possibility to opt out of it during production build).

**Comment by basarat** [comment]
I decided not to compete with storybook and do an unholy mix of docute + frontify https://frontify.com/. Will be ready very soon and that will make its use case more clear :rose:

**Comment by basarat** [comment]
@tomitrescak does this help your use case : https://formstate.github.io/#/?id=formstatelazy You maintain the array however you want. Or even add arrays *optionally* ?

**Comment by basarat** [comment]
@tomitrescak So the way we've been handling this is by maintaining *additional* validation rules regarding the overall form state in *our State* classes. 

But to make it easier to *just use formstate* just pushed a new version `0.10.0` that allows you to add validators to `FormState`. This works nice with your example. Also you don't need to make arrays observable since `FormState.$` is automatically made observable for you. Simplified your `Cars` / `Features` example further and used it as a tutorial here : https://formstate.github.io/demos/#formstate Hope you like it :rose: :heart:

**Comment by tomitrescak** [comment]
G'day mate :)! I saw your tweet and checked out the tutorial and was very happy with it! Thanks for the amazing work you are doing. Your effort is cutting down the development and refactoring time immensely and is just pleasure to work with it.
