### ISSUE TITLE
TypeScript type issue with FieldState

### ISSUE THREAD

**Issue by thupi** [formstate/formstate#41]
When i was trying to use formstate with a taginput i quickly ran into a problem. I was getting a type error when i was setting the default value of the FieldState as following: `new FieldState([])`. 

I get the following error message form typescript:
`TS2345:Argument of type 'string[]' is not assignable to parameter of type 'never[] | undefined'. Type 'string[]' is not assignable to type 'never[]'. Type 'string' is not assignable to type 'never'.`

I had to set the default value to `new FieldState([''])` in order to let the typesystem work. Is there something i can do to work arround this :-) ?

**Comment by basarat** [comment]
> new FieldState(['']) in order to let the typesystem work. Is there something i can do to work arround this :-)

:rose:
```js
new FieldState<string[]>([])
```
