### ISSUE TITLE
Double validation when validating on blur and onsubmit

### ISSUE THREAD

**Issue by joargp** [formstate/formstate#42]
I have validation onBlur on each input field. And on submit I call validate on the formstate containing all the fields.

When calling validate on the formstate, already validated fields are validated again. Is there any way to avoid this?

**Comment by basarat** [comment]
> Is there any way to avoid this?

Not built in. A validator might change its opinion on one field based on another field value. Form validation is somewhat transactional and does a full sweep. 

# External fix

You can inherit and create your own `AwesomeFieldState` and replace the logic on field validation to track `onChange` to skip validation in cases that matter to you :rose:
