### ISSUE TITLE
Problem with typescript and `onChange`

### ISSUE THREAD

**Issue by misantronic** [formstate/formstate#43]
Currently, the type for `onChange` looks like this: `onChange: (value: TValue) => void;`
Where `TValue` is the type I provided to `FieldState` e.g. `public myField: FieldState<number>;`

Now, passing other values than `number` to `onChange` will result in typescript complaining.
Shouldn't `onChange` accept any-type and leave it up to the validator? 
In any case I want my form-element to accept the value and validate it with a proper error-message.

**Comment by basarat** [comment]
> Shouldn't onChange accept any-type and leave it up to the validator

No. If you need to pass e.g. `string` and `numbers` to `onChange` then `TValue` *should be* `string | number`. 

Hope that helps :rose:
