### ISSUE TITLE
Breaking change to 1.0.0

### ISSUE THREAD

**Issue by KnisterPeter** [formstate/formstate#44]
Breaking change in the last version:
 `error TS2551: Property 'reinitValue' does not exist on type 'FieldState<number>'. Did you mean '_initValue'?`

It would be goodl to have a CHANGELOG or release notes where changes are visible.

**Comment by basarat** [comment]
https://github.com/formstate/formstate/commits/master

Its renamed to `reset` and now supported on `FormState` as well https://github.com/formstate/formstate/commit/5e6eefbe3fd8843740a905d98d6767ee35ad4963

Now that we are `1.0.0` will make change with a changelog but considering how stable it has been, don't expect to make (or approve) any changes. This project should just work as it is from now on :rose: 

Sorry for the inconvinience :heart:

**Comment by basarat** [comment]
> It would be goodl to have a CHANGELOG or release notes where changes are visible.

done https://github.com/formstate/formstate/blob/master/CHANGELOG.md :rose:

**Comment by KnisterPeter** [comment]
Thank you 🚀
