### ISSUE TITLE
async default value

### ISSUE THREAD

**Issue by Gi972** [formstate/formstate#46]
Hello,

Your component is great, but can you an in the demo an example with async value after  get values in ajax call in componentDidMount ? 
I mean when I want reset the form, I would like retrieve the  initial value from my data server object 
and no a empty field.

Thanks for the answer

**Comment by basarat** [comment]
> demo an example with async value after get values in ajax call in componentDidMount ?

```js
componentDidMount() {
   getSomeValue().then(val => state.someField.reset(val));
}
```

:rose:

**Comment by basarat** [comment]
You might want to disable the input or show a spinner or something while the value is being loaded :heart:

**Comment by Gi972** [comment]
Thank you @basarat 
Your tool is very very great! :-)
