### ISSUE TITLE
do not validate invalid values until they become valid 

### ISSUE THREAD

**Issue by misantronic** [formstate/formstate#47]
I have a `minLength`-validator, which simply checks on the length of a string.

```js
newPassword: new FieldState<string>('').validators(
        minLength(7, 'Password must be 7 chars or longer')
)
```

When changing the form-field with `field.onChange(value)` it immediately validates and the form is invalid.
Is there a way to tell `FieldState` to not validate until it once was valid?

**Comment by basarat** [comment]
You have complete control of the `validation triggering` mechanism. Docs https://formstate.github.io/demos/#validation-triggering :rose: 

Setup presented for 
* On every `onChange` (default)
* Explicit control (on submit etc)
* etc.

> Is there a way to tell FieldState to not validate until it once was valid

There needs to be more thought on this e.g. if the field is never valid then when does the user get the error? The API provided could be used to develop a solution for this though. You can easily extend `FieldState` to add any default behaviour you want :heart:
