### ISSUE TITLE
How do you set validation errors returned when trying to submit the form?

### ISSUE THREAD

**Issue by ghost** [formstate/formstate#49]
I've had a look through the documentation and the API, and I can't see a way to set form level validation errors which have been returned when submitting the form.

e.g.
Take a simple Login form...
When the form is submitted it's content is sent to the server, the server checks if the credentials are correct, and then returns either saying "success" or "Login failed".
If the login failed then that would often be displayed as a "form level" validation error.

It seems that this is possible at the field level, as (if I'm reading the source right) you can directly set the [`error` observable field](https://github.com/formstate/formstate/blob/master/src/core/fieldState.ts#L17). 

e.g.
A Register User form...
The Username field would have an async validator on it that checks if the username is available.
But the async validator doesn't reserve the username, it simply checks the availability at that moment in time.
When the user submits the form the server might reply with a validation failure as someone else has taken that username between the async validator running and the form actually being submitted.
And the client side code sets usernameFIeldState.error = "This username has already been taken."

Is doing this at the form level possible?

Or is it something I should be handling specially outside of form-state?

**Comment by ghost** [comment]
I don't think it's unreasonable to handle form level submit validation errors separately.

At the moment I'm using a simple observable string:

    @MobX.observable
    private formError = "";

    public render() {
        {this.formError &&
            <p>
                {this.formError}
            </p>
        }
    }

(Apologies if this kind of question is better suited to StackOverflow, I'll happily move the question if it's inappropriate to have it here.)

**Comment by basarat** [comment]
You can use FormState validators : https://formstate.github.io/#/?id=formstate-validators for issues *with the values in the form*. 

> "Login failed"

This feels like business logic and should be a part of `AppState` and your solution of 

```
@MobX.observable
private formError = "";
```
Is sufficient. I would call it `loginError` though : 

```
@MobX.observable
private loginError = "";
```
:rose:
