### ISSUE TITLE
Decorator support?

### ISSUE THREAD

**Issue by Eisenspalter** [formstate/formstate#5]
Is it possible to implement definitions as Decorators?

**Comment by basarat** [comment]
> implement definitions

You mean `validators` as decorators? If so, no. 

Reason: `field = new FieldState({value:'',validators:[required]})` vs `@required field = new FieldState({value:''})`. Although I appreciate the beauty of syntax 2, its significantly different in terms of implementation from what we have. A list a validators driven by field (what we have) vs. validators observing fields (what I imaging decorators would need to do). Hope that helps 🌹
