### ISSUE TITLE
how does formstate handle non-string data?

### ISSUE THREAD

**Issue by faassen** [formstate/formstate#51]
I haven't been able to find documentation guidance on this, so I'm asking here:

Let's say I have a field that maintains a number (I'm a typescript noob, but TValue would be of type number for the FieldState), but the displayed form value is text. Where do I plug in a renderer that turns the number into text for display purposes, and converts the text back into a number? I'd imagine such a converter to run before validation takes place, so I can treat the value as a number in there; the conversion failing is another sort of validation error.

Is the idea that in React code I also convert the number to a string before I pass it to the input value, and write a custom onChange that does the conversion to a string before I pass it to formstate? I.e. something like:

``
<input value={render(foo.value)} onChange={e => foo.onChange(convert(e.target.value))} />
``

'convert' would return a special sentinel (or just ``null``) in case the conversion fails, so that the validators can make use of this information and give appropriate output.

I'm looking for a way to define this back and forth translation as part of FieldState instead. I guess a TFormValue that's the value that's actually shown in the form as opposed to TValue that's the value that's maintained immediately.

**Comment by faassen** [comment]
I just realized that if the application codebase is in typescript as opposed to JS, the typechecker will ensure you implement the equivalent of render() and convert() in your React components. Am I on the right track?

**Comment by basarat** [comment]
You are on the right path. I added a demo to show it as well :rose:

**Comment by faassen** [comment]
Thanks for this explanation, that's what I thought. I will communicate a philosophical issue in a new topic.
