### ISSUE TITLE
Alternatives to wrapping fields

### ISSUE THREAD

**Issue by faassen** [formstate/formstate#52]
In a discussion on how to support non-string datatypes the recommendation was made, as elsewhere in the docs, to wrap underlying fields into new fields that are formstate specific. ( https://github.com/formstate/formstate/issues/51)

After some experience with forms we've become wary of wrapping input components into new ones. There's a tension between reusability and readability/customizability here. For the latter a flat form that uses the underlying form components is often nicer. (especially if validation error display is also wrapped, though that's of course not necessary -- Ant Design separates that into a Form.Item component). We obscure the documentation of form components by wrapping. For instance, we use Ant Design, and if we wrap everything directly, we cannot just refer developers to the Ant Design documentation anymore, but instead have to make people understand the new layer we've created on top of it.

We've therefore gone for another approach where we stick to the UI component library's UI components as much as possible. This example is antd specific but I'm trying to communicate the idea:

```
function validationProps(val) {
  return {
    validateStatus: val.hasError ? "error" : undefined,
    help: val.error
  };
}

function inputProps(val) {
  return {
    value: val.value,
    onChange: e => val.onChange(e.target.value)
  };
}
```

and we use these as follows with antd, where Form.Item and Input are direct imports from antd:

```
          <Form.Item
            {...formItemLayout}
            hasFeedback
            {...validationProps(username)}
          >
            <Input type="text" {...inputProps(username)} />
          </Form.Item>
```

This works well so far.

For fields that work with different data types like discussed in https://github.com/formstate/formstate/issues/51 , we can still create a higher-level wrapping and since we move outside of what antd offers, that's probably all right, though I want to explore whether perhaps something can be done with a clever inputProps instead.

A few questions:

* What is your opinion of this approach? perhaps you've seen problems with it that we haven't encountered yet.

* Would it make sense to expand the documentation to reference this as an alternative? I could try to write something up.

* Are there hooks we can discuss that would help support this API? the functions work, but of course I'd like to be able to write  ``username.validationProps()`` instead and save an import. We can't hardcode the antd behavior though, and I know you're wary of expanding the API too far. Could be accomplished by subclassing FieldState and using the subclass instead in form definitions -- are there any problems with that approach?

**Comment by basarat** [comment]
> What is your opinion of this approach?

I give my developers a simple component (pseudocode)

```
const TextInput = (props) => <Form.Item {...somethingsFromProps}>
            <Input type="text" {...someMoreThingsFromProps} />
          </Form.Item>
```
Reasons:
* I take responsibility for `TextInput`. It should just work. Internals are only a concern for common lib authors, not project authors.
* Decreases changes of typo's / copy past errors (e.g. they changed props to `Input` but forgot to change it for `Form.Item`) and invalid nesting of `Form.Item` and `Input` in project code (e.g. they felt like another div would be a good idea). 

> Could be accomplished by subclassing FieldState and using the subclass instead in form definitions

External subclassing is a first class citizen. Added to docs :rose:

**Comment by faassen** [comment]
Combining ``<Form.Item>`` and ``<Input>`` combines all the props (and there are quite a few in antd) of two separate components into a single one, which becomes rather more difficult to document, so that's a reason to avoid that approach. Your point about avoiding copy/paste errors is a good one though. For my own project I will just need to see how it develops and keep the wrapping approach in mind.
