### ISSUE TITLE
raw value versus converted value

### ISSUE THREAD

**Issue by faassen** [formstate/formstate#53]
Another philosophical comment in relation to https://github.com/formstate/formstate/issues/51

You wrote an example there:

https://github.com/formstate/formstate/commit/0175a65e6c20f0e66a44f116d8a6757a0d4b2141

Here you convert to ``null`` in case conversion cannot take place. The validator then needs to respond to the null case and handle it appropriately. To display the value in the input component, you convert null back to the empty string. This means that when you type non-string input, you see no input appear on the screen.

But what if I type "a123"? It's not an unreasonable UX to expect a validation error and then the ability to correct to 123, but I can't I won't be allowed to type at all.

To remedy this, ``NumberInputField`` could track of its raw input in an observable prop, and always render this into ``value``. If still passes along ``null`` if it cannot be converted to a string. And on initialization of the ``NumberInputField``, you'd need to initialize this raw value prop from ``fieldState``. But what if ``fieldstate`` is changed in the mean time by the program? How do we update the raw value in the ``NumberInputField``? We don't *always* want to update the raw value because in that case the act of typing would modify ``fieldState`` and we'd lose information.

Am I making things too complicated or is this a real usability issue with this approach? If this is a real issue, I think the framework should offer support for it, at the very least in the form of documentation.

**Comment by basarat** [comment]
> The validator then needs to respond to the null case and handle it appropriately.

Yes. Most validators should consider *null* to be *valid* and ignore it. Pushed more docs here : https://formstate.github.io/#/?id=tip-empty-values 

# Quote 
### TIP: Empty values

When the field is empty, the only validator that should consider it *invalid* should be the *required* validator. Most other validators should consider it as *valid*.

Example: Here is a *required* and *email* validator:

```ts
export const required: Validator<string | null | undefined> = (value) => {
  const error = "Value Required";
  if (value == null || !value.trim()) {
    return error;
  }
  return null;
}
export const email: Validator<string | null | undefined> = (value) => {
  // Empty values are not invalid emails
  if (required(email)) return null;
  value = value.trim();
  // Src : http://emailregex.com/
  if (!/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/g.exec(value)) {
    return "Not a valid email address";
  }
  return null;
}
```

This way if you just use `validators(email)` you do not get an error for empty values and only get an error on invalid emails when they are provided. If you use `validators(required,email)` you get an error for empty values plus invalid emails.

You can easily wrap your validator in a function that removes `TValue`s that you don't want to handle e.g

```ts
function ifValue(validator:Validator<TValue>):Validator<TValue | null | undefined>{
  return function(value: TValue) {
    if (!value || value == null) return null;
    return validator(value);
  };
}

// Usage
// validators: [ifValue(mySimplerValidator)]
```

**Comment by basarat** [comment]
> But what if I type "a123"? It's not an unreasonable UX to expect a validation error and then the ability to correct to 123, but I can't I won't be allowed to type at all.

There are two kinds of inputs. 
* Those that do not allow invalid data entry e.g. the number input shown in the demos. Another example is the browser select input. 
* Those that allow invalid data entry. You can try and avoid these with UX but I've added an example for a raw string based date input to the demos. The input handles raw *strings*. You do the type conversion on the fly as needed e.g. `if (!field.hasError) { /* safe to use */}` :rose: 

I've added a date to the demos: https://formstate.github.io/demos/#custom-type-tvalue :rose:

**Comment by faassen** [comment]
I understand the date example, and I think it's a useful addition to the doc (thank you!). 

I think FormState is still a bit stringly in this area... 😉

If I understand it correctly you *either* can let the user type raw values *or* get proper types from FieldStates, but not both. If you want both you're on your own and have to convert the string value in the FieldState yourself in application code. 

I am looking for more, as I think the form library could actually help with this by keeping track of the raw value as well as conversion itself.

What I'm looking for is a FieldState thas has a different type for ``value`` than it does for ``$``. ``$`` remains ``TValue``, but ``value`` could be different (typically a string), so ``TRawValue``. In such a case the developer needs to provide a ``convert`` function that converts the ``TRawValue`` to ``TValue``. The ``FieldState`` tracks the raw ``TRawValue`` separately. There are two kinds of validators -- those on the level of ``TValue``, and those on the level of ``TRawValue``. Once the ``TRawValue`` validators pass, the conversion to ``TValue`` happens, and the ``TValue`` validators do their work.  Once all validation succeeds, ``$`` is updated. If ``$`` is updated (directly or by the system), a ``render`` (the inverse of ``convert``, also supplied by the developer) runs that converts ``TValue`` to ``TRawValue``. Since ``$`` is only updated after successful validation, doing this is safe. Our current ``FieldState`` is a special case where ``TValue`` is ``TRawValue``, and identity functions for both ``convert`` and ``render``.

I know it's a big step, but are you willing to consider going in this direction? If yes I can try to sketch out some code.

**Comment by basarat** [comment]
> are you willing to consider going in this direction? If yes I can try to sketch out some code.

This is definitely a good idea. But not a direction I want to go in myself. 

Reason: This project is iceboxed in terms of concepts. This is because of certain things at work that require it needs to work as it is for as long as possible till the community does something simpler :rose:

**Comment by faassen** [comment]
So if I read you correctly, you would reject a PR that makes this modification. Is that correct?

**Comment by basarat** [comment]
> Is that correct?

Yes. But will try and work in it *way in the future* in case nothing better comes up :rose:

**Comment by basarat** [comment]
Added docs on how we handle it in our projects thats worked well for us : https://formstate.github.io/demos/all/#custom-type-tvalue 

Closing for now :rose:
