### ISSUE TITLE
Prevent recursively convertion within value?

### ISSUE THREAD

**Issue by nighca** [formstate/formstate#54]
Currently `FieldState` makes `value` observable recursively:

https://github.com/formstate/formstate/blob/a6cb85a5130f06456f1e43a1c5ef3383af2cddf9/src/core/fieldState.ts#L14

which makes there no chance for developers to decide it.

IMO, that is enough for formstate to make the `value` / `$` property observable (using [`observable.ref`](https://mobx.js.org/refguide/modifiers.html#reference-observability)). It should be developers' duty to decide if the value should be make observable recursively.

What do you think? @basarat

**Comment by basarat** [comment]
> which makes there no chance for developers to decide it.

Yes. This is intentional. Anything else would be more stuff to explain / show how to setup :rose:
