### ISSUE TITLE
Validating input in a grid with e.g. orderline input data (documentation)

### ISSUE THREAD

**Issue by trillian74** [formstate/formstate#56]
How would i use formstate when validating input in an input grid?

lets say i create lines and need to validate that quantity and deliverydate is set per row?

**Comment by basarat** [comment]
> lets say i create lines and need to validate that quantity and deliverydate is set per row?

`[row, row]` with each row being `{deliverderydate}` you have:

```ts
[{deliverydate},{deliverydate}]
//                             ^ validate this.
```
:rose:
