### ISSUE TITLE
mobX.toJS does not work as expected with FieldState

### ISSUE THREAD

**Issue by Eisenspalter** [formstate/formstate#6]
When using mobX.toJS to serialize the object, I expect that FieldState will be resolved to the field value
Example:

Declaration
````  
firstname = new FieldState({
    value: 'John',
    validators:[(val) => !val && 'Required']
});
```` 
after mobX.toJS
```` 
firstname: {
    value:'John',
    $:'John'
    ...
    ...
````
expected
````
firstname:'John'
````

**Comment by basarat** [comment]
It should resolve to what ever is the *type* determined by TypeScript. The type is `FormState` with `{value:string, $:string ...}`. Basically remove all *mobx* observable stuff and revert to native :rose:
