### ISSUE TITLE
disable particular fieldstate validator

### ISSUE THREAD

**Issue by Gi972** [formstate/formstate#60]
Hello @basarat,

I see we can disable autovalidation on a fieldstate
but it is possible disable or enable validation on a fieldstate 

example:

I have a radiobutton  with two inputs and each inputs have a required validation.

If  I choose the first input,  I want disable the second input validation  and this using the same validation method for the 2 inputs.

or in the FormState validators disable a validation.

the disableAutoValidation  works on fieldstate but when I validate form they are réactivate.

any solutions for this

If you can add a example I take

thanks

**Comment by basarat** [comment]
> If you can add a example I take

Track it as state eg. here is a general purpose wrapper

```ts
// Add types / generics / more methods ... good code 🌹
class OptionalValidator {
   constructor(public _validator){}
   enabled = true;
   validator = (val) => { return this.enabled ? this._validator(val) : null }
}

// use 
const optionallyRequired = new OptionalValidator((val) => !val && 'Value required');
new FieldState('').validators(optionallyRequired.validator);

// Required
optionallyRequired.enabled = true;
// Disabled 
optionallyRequired.enabled = false;
```

Or something simple that supports your use case.  e.g. 

```ts
const required = () => // .. some required validator ;
new FieldState('').validators((val) => { /* on some logic return required  otherwise null */});
```

**Comment by Gi972** [comment]
Thanks for the example @basarat  👍
