### ISSUE TITLE
MaterialUI example out of date

### ISSUE THREAD

**Issue by matijagrcic** [formstate/formstate#62]
Hi,

The demos are not valid anymore as the materialUI changed and they now use 
helperText and error properties respectively. 

Would like to update the docs.

**Comment by basarat** [comment]
PR will get merged instantly :rose: 

That said the concepts are the focus, not *how to use material ui*. Hopefully the concepts are clear 👌

**Comment by basarat** [comment]
Done https://formstate.github.io/demos/all/#creating-a-field :rose:
