### ISSUE TITLE
Switch on autovalidation on FormState

### ISSUE THREAD

**Issue by aschumahua** [formstate/formstate#66]
In this case autovalidation on `FormState` is not working, I mean `value => !value.Name.$.trim() && 'Value is required'` is not checking
```typescript
newTemplate = new FormState({
    Name: new InputFieldState<string>('name').validators(value => this.isNameUsed(value) && 'This name is used'),
    CampaignType: new DropdownFieldState<CampaignType>(CampaignType.Default)
}).compose().validators(value => !value.Name.$.trim() && 'Value is required');
```
Validator on `FormState` starts autovalidating only if `onChange` method of all the `FieldState`-s are called and changes theirs values.
```typescript
this.newTemplate.$.Name.onChange('');
this.newTemplate.$.CampaignType.onChange(CampaignType.IdleAccount);
```
Can you help me, please?

**Comment by basarat** [comment]
> Validator on FormState starts autovalidating only if onChange method of all the FieldState-s are called and changes theirs values

This is by design. FormState validation doesn't run automatically till all children are `valid`.

I'll add some docs :rose:

**Comment by aschumahua** [comment]
Can we add some changes to switch on FormState autovalidation right away when it is needed?

**Comment by basarat** [comment]
> Can we add some changes to switch on FormState autovalidation right away when it is needed?

`formState.enableAutoValidationAndValidate()` will do that 👍

**Comment by aschumahua** [comment]
> 
> 
> > Can we add some changes to switch on FormState autovalidation right away when it is needed?
> 
> `formState.enableAutoValidationAndValidate()` will do that 👍

@basarat Unfortunately `formState.enableAutoValidationAndValidate()` doesn't help with this, can you watch the example, please - https://codesandbox.io/s/pm59q0r650

In that case I can't make `FormState` validator work without changing `type`.

**Comment by basarat** [comment]
Thank you for your excellent reproduction and patience. Sorry for the previous poor design choice on when to fire form validators (`onChangeAfterValidationPass`). Changed to match your (and now mine) intuition (`onValidationPass`) :+1: 
`1.3.0` :rose:
