### ISSUE TITLE
Inconsistent autovalidation API behavior

### ISSUE THREAD

**Issue by winseros** [formstate/formstate#67]
The form autovalidation 'enable' and 'disable' methods have inconsistent behavior:

* [enableAutoValidation](https://github.com/formstate/formstate/blob/b623a049d784234dce0845d9ac2ea7b497f8cf99/src/core/formState.ts#L159): enables validation **both** for the form itself **and** for its children fields
* [enableAutoValidationAndValidate](https://github.com/formstate/formstate/blob/b623a049d784234dce0845d9ac2ea7b497f8cf99/src/core/formState.ts#L163): enables validation **only** for the form, and **not** for the children fields
* [disableAutoValidation](https://github.com/formstate/formstate/blob/b623a049d784234dce0845d9ac2ea7b497f8cf99/src/core/formState.ts#L167): disables validation **only** for the form, and **not** for the children fields

It would be nice having consistency in these kinds of methods. E.g. make the `enableAutoValidationAndValidate` and `disableAutoValidation` influence on the children fields, as the `enableAutoValidation` does.

**Comment by basarat** [comment]
Agreed. Sorry some poor code by me here : https://github.com/formstate/formstate/blob/8a73701bdc278082b6b290b395088d4f3e28b995/src/core/formState.ts#L155-L169

**Comment by basarat** [comment]
`1.2.0` :rose:
