### ISSUE TITLE
Allow validators to be specified in FieldState constructor

### ISSUE THREAD

**Issue by DanielSWolf** [formstate/formstate#7]
The `FieldState` constructor takes an options object, allowing things like value and auto-validation to be specified. I find it surprising that I cannot also specify validators there.

I'd prefer to write this:

```js
username = new FieldState({
  value: '',
  validators: [required]
});
```

instead of this:

```js
username = new FieldState({
  value: '',
}).validators(required);
```

Is there a reason why this syntax is not supported?

**Comment by basarat** [comment]
We actually changed this very recently (last week). Here are a few reasons why the new format:

* Previously validators can mess with generic inference 

Having them in the constructor meant that some general purpose validators (that work with unions like `string | number | boolean | null | undefined`) would change the inferred type of the `FieldState`. Moving them out of the constructor means only `value` gets to decide the inference

* Var args 

Having validators pass in as var args / rest parameters means that people don't try to mutate the array of validators passed in after giving it to us. No biggie but still 👍 

* Consistency with FormState 

This is the big one, We recently added validators to FormState : https://formstate.github.io/#/?id=formstate-validators Forms currently don't take additional arguments, only value as contructor param, so we added validators to FormState as a chained call. We like the *single argument drives the generics* way that FormState currently works . Made sense to make FieldState consistent :rose: 


> If you like this project, ⭐️ it ❤️
