### ISSUE TITLE
Another formstate

### ISSUE THREAD

**Issue by nighca** [formstate/formstate#76]
Hi @basarat !

We like formstate (especially its simple API) very much and we used formstate a lot in our projects.

However there are some problems on which we hold different points. So we built “another formstate” to satisfy our own needs. We call it **[formstate-x](https://github.com/qiniu/formstate-x)**. It provides similar APIs with formstate, but with almost totally different realization. We thought that might help others, too (with issues like #11 #25 #28 #34 #54).

If you don't mind, I want to introduce it to users of formstate, just as another optional choice. And if you have any suggestions for use, that will be very welcomed:)

**Comment by basarat** [comment]
Lovely. Thanks for sharing! :rose:

Happy to take a PR to the readme / docs linking to formstate-x as alternatives :heart:

**Comment by nighca** [comment]
@basarat Great! And here is the PR #77

**Comment by basarat** [comment]
Merged. Thanks :rose:
