### ISSUE TITLE
Clearly state about maintainability status in README

### ISSUE THREAD

**Issue by kubk** [formstate/formstate#78]
Hi @basarat Thank you for the library. This comment https://github.com/formstate/formstate/pull/73#issuecomment-552612648 made me write it. 
If this library isn't going to be maintained or it is frozen and no new features will be added it should be stated in README. It will save time for those who are searching for a Mobx-based form library. Again, thank you for your work!

**Comment by basarat** [comment]
Its frozen. Not unmaintained. I use it heavily. It's more like stable : https://nodejs.org/api/documentation.html#documentation_stability_index 

It will continue to work with newer mobx / react releases. If that changes in the future I will update the readme :rose:
