### ISSUE TITLE
Cross field validation in onChange of a field

### ISSUE THREAD

**Issue by procedular** [formstate/formstate#8]
There is currently no way to register a validator in a field, that needs to read the value from another field, is there?

I like your validation concept very much and we are using ```mobx``` and ```mobx-react``` in our project, so your validation framework could fit very well. But one of our reasons why we are looking for a framework anyway, is to easily define cross field validators which should be triggered on changing a specific input field.

Will there be an other method to trigger those validators, besides manually calling the  ```validate``` function of the surrounding form? Or is there any smart way to structure the  ```FormState```s and  ```FieldState```s to achieve this? Or is there already a method how validators can read values from other fields?

**Comment by basarat** [comment]
> But one of our reasons why we are looking for a framework anyway, is to easily define cross field validators which should be triggered on changing a specific input field.

You can pass a handler to `onUpdate` for any FieldState, check if the value is valid and trigger a validation on another field

Alternatively trigger the form validation form validation on a fieldState `onUpdate` :rose:

**Comment by procedular** [comment]
Thanks for the prompt answer.

> Alternatively trigger the form validation form validation on a fieldState onUpdate 🌹

But the form validation is triggering the field update, isn't it? Sounds like an endless loop?

And the ```onUpdate``` callback gets called twice on changing the value of the field ...at least in my tests, is this normal?

**Comment by basarat** [comment]
> onUpdate callback gets called twice on changing the value of the field

yes. onUpdate is called on any change the field (error or value). Thinking through improving the UX. Currently busy with another OSS project https://github.com/basarat/yester. Will come back to this after that. 

Summary : you need to track changes (we can do that for you after I come back) and you need to track field  vs. form errors (we can do that after I come back). Key difficulty is thinking through the API but had good chat with friends at work :rose:

**Comment by basarat** [comment]
Quick question, your thoughts:

-  New field constructor arugments that replace `onUpdate`: `on$Change(prev:TValue, next:TValue)`, `onValueChange(prev:TValue,next:TValue)` and `onErrorChange(prev: string|null, error:string|null)` 

- Also FormState will get `hasFieldError` and `hasFormError`

> PS : Reason why I'm not using an event emitter (like https://gist.github.com/basarat/46936dec14ad985bee24f54f3977cb2d) is that it leads to memory leaks if users subscribe but forget to unsubscribe (that is another thing I'd have to teach and increases the chance of dev error for simple forms). So just doing single callbacks.

**Comment by basarat** [comment]
Discussion notes : https://github.com/formstate/formstate/issues/8#issuecomment-276622588 your thoughts appreciated :rose:

**Comment by procedular** [comment]
From the perspective of a consumer, i would rather use it like the other validators...
```
fieldState.validators(someCrossFieldValidator, ...other);
```
Assuming that the field supplies its validators with values from other fields.
```
function someCrossFieldValidator(value, formValues) {
  // do some validation with values from other fields and return
}
```
But this potentially breaks your concept of an encapsulated field?

**Comment by procedular** [comment]
But an ```onChange``` handler that only gets triggered when the value changes would be an alternative - a bit unconvenient from our perspective.

**Comment by basarat** [comment]
> fieldState.validators(someCrossFieldValidator, ...other);

You can already do that. In fact we had docs about it as well : https://github.com/formstate/formstate/commit/867e02cf32113050e59d3f34a0c6286e5b5fdb3b#diff-709384f5c992b1e62ed4d43183640edcL357 if you want :rose:

But the discussion I had with other devs was they want errors against the `Form` and not the `Field` as its difficult to say which of the field should have the error.

Again : will have more guidance soon :rose:

**Comment by basarat** [comment]
@alxkhr you can checkout the demo https://formstate.github.io/demos/#cross-field-validation released with `0.11.0` :heart:

**Comment by procedular** [comment]
You were right, declaring the cross field validation as part of the ```FormState``` does make more sense in the end. Thank you for pointing out! 💚 

But i wonder why you only re-validate the form if it has no error. This way it won't notice the invalid state caused by the cross field validator, when the form was valid before changing an affected field. Plus, i don't understand the reason why ```form.hasFormError``` is necessary anyway. 😳

**Comment by basarat** [comment]
> But i wonder why you only re-validate the form if it has no error.

Its a choice I leave to you. Similar to `onBlur` behavior where you want to validate live vs. validate live starting from on onBlur. You can replace it with `!hasFieldError` or any other condition you want to tune your UX for.

> Plus, i don't understand the reason why form.hasFormError is necessary anyway

To only show the error if *form* has an error cause of its validations. Otherwise in case of a field error you would potentially be showing the error against the field & the form. Hope that helps :rose:
