### ISSUE TITLE
What is the best way to add validation conditinaly?

### ISSUE THREAD

**Issue by da1z** [formstate/formstate#84]
Use case i have one formFieldA and I want to validate second form field only if formFIeldA.$ is true. What is the best way to achieve that?

**Comment by gustavohenke** [comment]
What did you try?
FormState validators are simple functions, so you can add whatever condition in it.

```js
const form = new FormState({
	fieldA: new FieldState(),
	fieldB: new FieldState(),
})

form.$.fieldB.validators(value => {
	if (form.$.fieldA.$) {
		// do validation
	}
});
```
