### ISSUE TITLE
using formstate with yup

### ISSUE THREAD

**Issue by branikclimbs** [formstate/formstate#86]
Is it possible to use formstate with [yup](https://github.com/jquense/yup) for validation?

**Comment by gustavohenke** [comment]
yup 😜 

This is roughly of what I have as an util function (e.g. `withSchema(field, schema)`:

```js
new FieldState().validators(value => {
	try {
		someSchema.validateSync(value);
	} catch (e) {
		if (e instanceof ValidationError) {
			return e.message;
		}

		throw e;
	}
})
```

**Comment by branikclimbs** [comment]
thanks @gustavohenke :)
